### ISSUE TITLE
SUCCEEDED - Execution output:  {}: Found error logs for timeout in executor for 12000 ms

### ISSUE THREAD

**Issue by StianHanssen** [alexcasalboni/aws-lambda-power-tuning#140]
I ran your tool on a lambda that is very CPU intensive to process a 2 minute video.

I understood from issue https://github.com/alexcasalboni/aws-lambda-power-tuning/issues/59 that `execution.sh` is more of a guideline and that `SUCCEEDED` is likely flawed, so I had a look at the metrics and found errors in the executor lambda. I checked the logs and found:

```
Field | Value
@ingestionTime | 1632647091033
@log | 540160934250:/aws/lambda/serverlessrepo-aws-lambda-power-tuning-executor-J3aF1SJBlOij
@logStream | 2021/09/26/[$LATEST]9f530540144e43b4a70ff0f294cab7d1
@message | 2021-09-26T09:04:42.010Z c086167a-3c7e-48c6-8557-577dd98f281e ERROR Invoke Error {"errorType":"TimeoutError","errorMessage":"Connection timed out after 120000ms","code":"TimeoutError","message":"Connection timed out after 120000ms","time":"2021-09-26T09:04:42.010Z","region":"us-east-1","hostname":"lambda.us-east-1.amazonaws.com","retryable":true,"stack":["TimeoutError: Connection timed out after 120000ms"," at ClientRequest.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/http/node.js:86:34)"," at Object.onceWrapper (events.js:519:28)"," at ClientRequest.emit (events.js:400:28)"," at ClientRequest.emit (domain.js:470:12)"," at TLSSocket.emitRequestTimeout (_http_client.js:790:9)"," at Object.onceWrapper (events.js:519:28)"," at TLSSocket.emit (events.js:412:35)"," at TLSSocket.emit (domain.js:470:12)"," at TLSSocket.Socket._onTimeout (net.js:484:8)"," at listOnTimeout (internal/timers.js:557:17)"]}
@requestId | c086167a-3c7e-48c6-8557-577dd98f281e
@timestamp | 1632647082011
code | TimeoutError
errorMessage | Connection timed out after 120000ms
errorType | TimeoutError
hostname | lambda.us-east-1.amazonaws.com
message | Connection timed out after 120000ms
region | us-east-1
retryable | 1
stack.0 | TimeoutError: Connection timed out after 120000ms
stack.1 | at ClientRequest.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/http/node.js:86:34)
stack.2 | at Object.onceWrapper (events.js:519:28)
stack.3 | at ClientRequest.emit (events.js:400:28)
stack.4 | at ClientRequest.emit (domain.js:470:12)
stack.5 | at TLSSocket.emitRequestTimeout (_http_client.js:790:9)
stack.6 | at Object.onceWrapper (events.js:519:28)
stack.7 | at TLSSocket.emit (events.js:412:35)
stack.8 | at TLSSocket.emit (domain.js:470:12)
stack.9 | at TLSSocket.Socket._onTimeout (net.js:484:8)
stack.10 | at listOnTimeout (internal/timers.js:557:17)
time | 2021-09-26T09:04:42.010Z
```

The perplexing part for me was that I configured both my own lambda and this tool to have a timeout of 900 seconds (900000 ms), so it shouldn't be timing out at 120000 ms. Could there be a place where it has been hard-coded to timeout after 2 minutes?

Testing with a shorter video allowed me to execute without issues, but I would prefer to test as closely to a real production environment as possible. In manual testing with memory 10240 I have confirmed the lambda can process the video in 72000 ms,  but I suspect the lambda may time out on low settings. That said, it shouldn't time out after 120000 ms.

**Comment by alexcasalboni** [comment]
Thanks for sharing, @StianHanssen! Yes it’s possible that some power configurations fail, based on memory of compute time. Right now the tools assumes that all the tested power configurations have enough memory and sufficiently long timeout. Totally agree that it could be easier to understand where and why the state machine failed, without inspecting intermediate steps.

Please do share additional details about the connection timeout, so we can find a way to handle it and/or document it.

**Comment by StianHanssen** [comment]
@alexcasalboni Hi, sorry for the late reply. The cause is as a posted in my previous message. The AWS SDK has a constant in its config about connection timeout threshold for http requests. This timeout is set to 2 minutes. This means that if you make an synchronous invoke to a lambda, it will keep a socket open to await the response, but if that response doesn't return within 2 minutes, it will retry and eventually crash out.

Set this configuration in the lambda which performs the invoke:
```
AWS.config.update({httpOptions: {timeout: <the lambda's timeout value in ms>}});
```
It is this configuration above that is configured to be 2 minutes by default.

**Comment by alexcasalboni** [comment]
Thanks @StianHanssen! I'll look into this asap :) 

I think it makes sense to set this value to `totalExecutionTimeout` (the CloudFormation input parameter, which is 5 minutes by default). But 15min could be an easy fix as well since the function execution will timeout anyway.
