### ISSUE TITLE
ResourceNotFoundException: Functions from 'us-east-1' are not reachable in this region ('us-west-1')

### ISSUE THREAD

**Issue by gvasquez-waypoint** [alexcasalboni/aws-lambda-power-tuning#18]
Seems like cross region usage is not available for lambdas so, the Step Function should be deployed on each region, am I right, or is it just a coding restriction and can be improved?

Full trace from CloudWatch Logs:

`START RequestId: c48d4975-d571-46d7-9835-9a7f84e0300f Version: $LATEST
2019-05-14T13:32:20.857Z	c48d4975-d571-46d7-9835-9a7f84e0300f	{ ResourceNotFoundException: Functions from 'us-east-1' are not reachable in this region ('us-west-1')
at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)
message: 'Functions from \'us-east-1\' are not reachable in this region (\'us-west-1\')',
code: 'ResourceNotFoundException',
time: 2019-05-14T13:32:20.857Z,
requestId: 'b3418c32-764c-11e9-ab60-7505d4afde13',
statusCode: 404,
retryable: false,
retryDelay: 52.181729400208376 }
2019-05-14T13:32:20.932Z	c48d4975-d571-46d7-9835-9a7f84e0300f	Error: Interrupt
at /var/task/initializer.js:68:27
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-05-14T13:32:20.932Z	c48d4975-d571-46d7-9835-9a7f84e0300f	Error: Interrupt
at /var/task/initializer.js:68:27
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-05-14T13:32:20.932Z	c48d4975-d571-46d7-9835-9a7f84e0300f	Error: Interrupt
at /var/task/initializer.js:68:27
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-05-14T13:32:20.932Z	c48d4975-d571-46d7-9835-9a7f84e0300f	Error: Interrupt
at /var/task/initializer.js:68:27
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-05-14T13:32:20.932Z	c48d4975-d571-46d7-9835-9a7f84e0300f	Error: Interrupt
at /var/task/initializer.js:68:27
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
2019-05-14T13:32:20.934Z	c48d4975-d571-46d7-9835-9a7f84e0300f
{
    "errorMessage": "Interrupt",
    "errorType": "Error",
    "stackTrace": [
        "/var/task/initializer.js:68:27",
        "<anonymous>",
        "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
    ]
}

END RequestId: c48d4975-d571-46d7-9835-9a7f84e0300f
REPORT RequestId: c48d4975-d571-46d7-9835-9a7f84e0300f	Duration: 1510.06 ms	Billed Duration: 1600 ms Memory Size: 128 MB	Max Memory Used: 59 MB	`

**Comment by alexcasalboni** [comment]
Hi @gvasquez-waypoint, I've looked into this and you are right: at the moment you'd need to deploy the state machine to each region, but that's definitely not ideal.

Basically, the current code is assuming the Lambda function you are tuning is in the same region of the state machine.

And that happens because [here](https://github.com/alexcasalboni/aws-lambda-power-tuning/blob/master/lambda/utils.js#L95) I am not forcing any specific region. I'd need to extract the region name from the Lambda ARN, and then invoke the correct endpoint.

Let me work on it today, it should be an easy fix :)

**Comment by alexcasalboni** [comment]
Fixed :)

I'm going to publish a new version of this app in the Serverless Application Repository as well.

Thank you again for reporting this issue 🙏 💯

**Comment by gvasquez-waypoint** [comment]
Superb ultra fast response from your side! I'm wondering if I must drop the stack or a new "pull" from GIT and running again deploy.sh would work to use your fix

**Comment by alexcasalboni** [comment]
Yes, git pull and re-deploy to the same stack should work fine!

**Comment by gvasquez-waypoint** [comment]
Done:
```
> git  pull
> source ./deploy.sh
```

Re-tested cross-region and now works ok!
