### ISSUE TITLE
Unrecognized JSON log error

### ISSUE THREAD

**Issue by guillaume-gc** [alexcasalboni/aws-lambda-power-tuning#261]
I'm experimenting with this tool, which is amazing! Unfortunately, I'm getting this error:
```
2024-10-03T15:20:17.838Z	e6ffdb72-1be8-4e9d-90f4-b66850933570	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Unrecognized JSON log",
    "stack": [
        "Error: Unrecognized JSON log",
        "    at module.exports.extractDurationFromJSON (/var/task/utils.js:673:11)",
        "    at module.exports.extractDuration (/var/task/utils.js:616:22)",
        "    at /var/task/utils.js:544:22",
        "    at Array.map (<anonymous>)",
        "    at module.exports.parseLogAndExtractDurations (/var/task/utils.js:538:17)",
        "    at computeStatistics (/var/task/executor.js:197:34)",
        "    at module.exports.handler (/var/task/executor.js:77:12)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
}
```

Here is some context, with all information redacted:
```
2024-10-03T15:20:17.837Z	e6ffdb72-1be8-4e9d-90f4-b66850933570	ERROR	Detected invalid JSON line: 
{
    "PutRequest": {
        "Item": {
            "PK": "REDACTED",
            "SK": "REDACTED",
            "ResourceType": "REDACTED",
            "ResourceId": "REDACTED",
            "ResourceSubject": "REDACTED",
            "VersionId": "REDACTED,
            "ChannelType": "REDACTED",
            "TeamId": "REDACTED",
            "CreatedAt": -1,
            "CreatedBy": "REDACTED",
            "InternalVersionId": "REDACTED"
        }
    }
}
]}}}
```

I assume the issue is caused by the `]` character?

Here is log that appears to be causing the issue:
```
{
    "cold_start": false,
    "function_arn": "REDACTED:RAM8182",
    "function_memory_size": "8182",
    "function_name": "REDACTED",
    "function_request_id": "REDACTED",
    "level": "DEBUG",
    "message": "REDACTED",
    "sampling_rate": 0,
    "service": "REDACTED",
    "timestamp": "REDACTED",
    "xray_trace_id": "REDACTED",
    "teamId": "REDACTED",
    "resourceId": "REDACTED",
    "resourceType": "REDACTED",
    "env": "REDACTED",
    "gitBranch": "REDACTED",
    "tenant": "REDACTED",
    "input": {
        "RequestItems": {
            "REDACTED": [
                {
                    "PutRequest": {
                        "Item": {
                            "PK": "REDACTED",
                            "SK": "REDACTED",
                            "ResourceType": "REDACTED",
                            "ResourceId": "REDACTED",
                            "ResourceSubject": "REDACTED",
                            "VersionId": "REDACTED",
                            "ChannelType": "REDACTED",
                            "TeamId": "REDACTED",
                            "CreatedAt": -1,
                            "CreatedBy": "REDACTED",
                            "InternalVersionId": "REDACTED"
                        }
                    }
                },
                {
                    "PutRequest": {
                        "Item": {
                            "PK": "REDACTED",
                            "SK": "REDACTED",
                            "ResourceType": "REDACTED",
                            "ResourceId": "REDACTED",
                            "ResourceSubject": "REDACTED",
                            "VersionId": "REDACTED",
                            "ChannelType": "REDACTED",
                            "TeamId": "REDACTED",
                            "CreatedAt": -1,
                            "CreatedBy": "REDACTED",
                            "InternalVersionId": "REDACTED"
                        }
                    }
                }
            ]
        }
    }
}
```

Here is the Step Functions input, without the `payload` key:
```
{
  "lambdaARN": "REDACTED",
  "num": 25,
  "powerValues": [
    "128",
    "256",
    "512",
    "1024",
    "2048",
    "4096",
    "8182"
  ],
  "parallelInvocation": false,
  "dryRun": false,
  "onlyColdStarts": false,
  "discardTopBottom": 0.2
}
```

**Comment by alexcasalboni** [comment]
Hi @guillaume-gc 👋  thanks for sharing!

This is probably a duplicate of #253 :) 

Thanks for sharing the logs as well! There seems to be some kind of problem with the JSON formatting (is it multi-line?). What kind of logger are you using? Is it Lambda Power Tools?

Could you please share the raw log lines? (without formatting or multi-line)

Context: Lambda Power Tuning assumes that there is one log per line (separated by `\n`), which is what CloudWatch does by default. If the log is "prettified" or split into multiple lines, it becomes problematic.

**Comment by alexcasalboni** [comment]
@guillaume-gc  ah, that's interesting! is it possible that DEBUG logs are prettified intentionally to improve the debugging experience? 🤔

**Comment by guillaume-gc** [comment]
@alexcasalboni as far as I know, no this is not the case.

Here is an example of a INFO log, still in plain text:
```
{
    "cold_start": true,
    "function_arn": "REDACTED",
    "function_memory_size": "128",
    "function_name": "REDACTED",
    "function_request_id": "REDACTED",
    "level": "INFO",
    "message": "Query is authorized",
    "sampling_rate": 0,
    "service": "REDACTED",
    "timestamp": "REDACTED",
    "xray_trace_id": "REDACTED"
}
```

As you can see, it's also prettified. Same with ERROR or WARNING log message.

The only difference I see between logs that are causing the issue and those who are not is the prettified array, and the error message also only included an array closing bracket. It could just be coincidental of course, I don't have enough example to notice a real pattern.

**Comment by patmeiler** [comment]
Hi @guillaume-gc  I'm working on a fix, but I can't reproduce the error. Could you tell me in which region you deploy your code? The other issue mentions something about the China region.

**Comment by patmeiler** [comment]
@alexcasalboni in the code, we invoke the Lambda by using the `Invoke` action (duh, right?!). Part of the response is `LogResult`, the last 4 KB of base64-encoded execution log. My hypothesis is, that in some cases, the `durationMs` is not part of the 4KB anymore. 
I am currently working on improved JSON handling and better error logs. But I'm also researching how to mitigate the issue.

**Comment by alexcasalboni** [comment]
@adambezecny a fix has been merged 👌  apologies for the very long wait :)

Please feel free to reopen this issue in case the problem shows up again (note: you'll need to deploy the state machine again, from the main branch).
