### ISSUE TITLE
Invocation error with Cannot read property of undefined

### ISSUE THREAD

**Issue by ChandrewR** [alexcasalboni/aws-lambda-power-tuning#74]
Though the execution succeeded, it shows error and empty object in Output

The input i passed is below as mentioned in guide: I changed the arn with my lambda arn. 

{
    "lambdaARN": "your-lambda-function-arn",
    "powerValues": [128, 256, 512, 1024, 2048, 3008],
    "num": 10,
    "payload": {},
    "parallelInvocation": true,
    "strategy": "cost"
}

Should i pass payload? 

Here is the complete error:

{
  "error": "Error",
  "cause": {
    "errorType": "Error",
    "errorMessage": "Invocation error: {\"errorType\":\"TypeError\",\"errorMessage\":\"Cannot read property 'id' of undefined\",\"trace\":[\"TypeError: Cannot read property 'id' of undefined\",\"    at Runtime.module.exports.get [as handler] (/var/task/todos/get.js:13:32)\",\"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)\"]}",
    "trace": [
      "Error: Invocation error: {\"errorType\":\"TypeError\",\"errorMessage\":\"Cannot read property 'id' of undefined\",\"trace\":[\"TypeError: Cannot read property 'id' of undefined\",\"    at Runtime.module.exports.get [as handler] (/var/task/todos/get.js:13:32)\",\"    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)\"]}",
      "    at /var/task/executor.js:114:19",
      "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
      "    at async Promise.all (index 1)",
      "    at async runInParallel (/var/task/executor.js:119:5)",
      "    at async Runtime.module.exports.handler (/var/task/executor.js:31:19)"
    ]
  }
}

**Comment by ChandrewR** [comment]
The lambda is expecting id value which i didn't pass. So i just tried with simple GET lambda with no parameters. How can i pass values in execution?

**Comment by alexcasalboni** [comment]
Hi @ChandrewR, thanks for reaching out :)

Yes you should include the expected input in the `payload` field.

If you want to simulate an Amazon API Gateway trigger, you can include everything in the payload (path, method, GET parameters, etc.).

Let me know if you manage to resolve this.

**Comment by ChandrewR** [comment]
Hi @alexcasalboni,

I tried passing payload like this, but failed with same above error again.

{
  "lambdaARN": "arn:aws:lambda:ap-south-1:<acc>:function:serverless-rest-api-with-dynamodb-dev-get",
  "powerValues": [
    128,
    256,
    512,
    1024,
    2048,
    3008
  ],
  "num": 10,
  "payload": {
    "id": "73bd03d0-8462-11ea-99ad-7dfd3eee325b"
  },
  "parallelInvocation": true,
  "strategy": "cost"
}

**Comment by alexcasalboni** [comment]
@ChandrewR what does the expected payload look like?

You are using this:

```json
{
    "id": "73bd03d0-8462-11ea-99ad-7dfd3eee325b"
}
```

If the error message is still `"Cannot read property 'id' of undefined"`, I'd guess your Lambda function is expecting a different structure. So I'd double-check your handler to verify this. Maybe you can share a minimal version of your handler here? (what happens at line 13?)

**Comment by ChandrewR** [comment]
Here it is,

'use strict';

//const AWS = require('aws-sdk'); // eslint-disable-line import/no-extraneous-dependencies
const AWSXRay = require('aws-xray-sdk');
const AWS = AWSXRay.captureAWS(require('aws-sdk'));

const dynamoDb = new AWS.DynamoDB.DocumentClient();

module.exports.get = (event, context, callback) => {
  const params = {
    TableName: process.env.DYNAMODB_TABLE,
    Key: {
      id: event.pathParameters.id,
    },
  };
.......code goes after this..

Its expecting id from event.pathParameters..This lambda is configured to API Gateway though..

**Comment by alexcasalboni** [comment]
Thanks for sharing :)

Your function expects `event.pathParameters.id`, so your payload will need to look like this:

```json
{
  "pathParameters": {
    "id": "XYZ" 
  }
}
```

**Comment by ChandrewR** [comment]
Whoa!! Thanks a lot Alex Casalboni. It worked like a charm.
